<?php

/*
 * This file is part of the FileGator package.
 *
 * (c) Milos Stojanovic <alcalbg@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE file
 */

namespace Filegator\Controllers;

use Filegator\Config\Config;
use Filegator\Kernel\Request;
use Filegator\Kernel\Response;
use Filegator\Kernel\StreamedResponse;
use Filegator\Services\Audit\ReportStore;
use Filegator\Services\Auth\AuthInterface;
use Filegator\Services\Auth\MfaLockout;
use Filegator\Services\Auth\RequiresStepUpAuth;
use Filegator\Services\Logger\LoggerInterface;
use Filegator\Services\Mfa\MfaService;
use Symfony\Component\HttpFoundation\HeaderUtils;

/**
 * Admin access to the reports generated by `php bin/filegator report:monthly`.
 *
 * Both routes are admin-only, enforced by role at route registration
 * (routes.php) rather than in here — a non-admin never gets the route into the
 * dispatcher and receives a 404, matching the convention AdminTest already
 * asserts for /admin/audit-log.
 *
 * The download is a POST, not a GET, and that is deliberate. Security::init
 * skips CSRF validation entirely for GET/HEAD/OPTIONS, and session cookies are
 * SameSite=Lax, which still sends them on a top-level cross-site navigation. A
 * GET route would therefore let an attacker page force a logged-in admin's
 * browser to write a CONFIDENTIAL CSV of every user's file activity into their
 * Downloads folder. POST gets CSRF for free and carries the step-up fields.
 *
 * Step-up matches how AdminController gates user CRUD: a month of everyone's
 * activity is at least as sensitive, and the pull-based version this replaces
 * required an explicit confirm dialog. Session cookie alone would be weaker
 * than both precedents.
 */
class ReportsController
{
    use RequiresStepUpAuth;

    protected $auth;

    protected $logger;

    public function __construct(AuthInterface $auth, LoggerInterface $logger)
    {
        $this->auth = $auth;
        $this->logger = $logger;
    }

    /**
     * Metadata only — never event data. Period, counts, coverage and size are
     * enough to choose a report; usernames and paths stay in the ciphertext.
     */
    public function index(Response $response, ReportStore $store)
    {
        $reports = array_map(function (array $row) {
            return [
                'id' => $row['id'] ?? '',
                'period' => $row['period'] ?? '',
                'filename' => $row['filename'] ?? '',
                'events' => $row['events'] ?? 0,
                'bytes' => $row['bytes'] ?? 0,
                'coverage' => $row['coverage'] ?? 'complete',
                'generated_at' => $row['generated_at'] ?? 0,
            ];
        }, $store->listReports());

        return $response->json(['reports' => $reports]);
    }

    public function download(
        Request $request,
        Response $response,
        StreamedResponse $streamedResponse,
        ReportStore $store,
        MfaService $mfa,
        MfaLockout $lockout,
        Config $config
    ) {
        $check = $this->stepUpForAdmin($request, $response, $mfa, $lockout, $config);
        if (! $check['ok']) {
            return $response;
        }

        // Take a PERIOD, not a filename or an id. User input then never reaches
        // the filesystem at all: the period is matched against the index the
        // cron itself wrote, and the stored filename comes from there. This
        // removes the traversal class rather than filtering it — there is no
        // string to sanitise and no path to concatenate.
        $period = (string) $request->input('period', '');

        if (preg_match('/^\d{4}-\d{2}$/', $period) !== 1) {
            return $response->json('File not found', 404);
        }

        $meta = $store->findByPeriod($period);
        if ($meta === null) {
            // Byte-identical to the malformed-period response above, so this is
            // not an oracle for which periods exist.
            return $response->json('File not found', 404);
        }

        $csv = $store->readDecrypted($meta['id']);
        if ($csv === null) {
            // NOT an empty body. decrypt() also returns null when the key file
            // cannot be read — for instance created root-owned by a cron run as
            // the wrong user — and a 200 with an empty CSV would be a silently
            // wrong compliance artifact.
            $this->logger->log(
                'Activity report '.$period.' could not be decrypted; check private/reports_encryption.key ownership',
                \Monolog\Logger::WARNING
            );

            return $response->json('Report could not be read', 500);
        }

        // This is the moment a month of PII leaves the encrypted store, so the
        // record has to survive production's WARNING log level.
        $actor = $this->auth->user();
        $this->logger->log(sprintf(
            'Activity report %s (%d events) downloaded by %s',
            $period,
            $meta['events'] ?? 0,
            $actor ? $actor->getUsername() : 'unknown'
        ), \Monolog\Logger::WARNING);

        $filename = $meta['filename'] ?? ('filegator-activity-CONFIDENTIAL-'.$period.'.csv');

        $streamedResponse->setCallback(function () use ($csv) {
            echo $csv;
            if (ob_get_level() > 0) {
                ob_flush();
            }
            flush();
        });

        $streamedResponse->headers->set(
            'Content-Disposition',
            HeaderUtils::makeDisposition(HeaderUtils::DISPOSITION_ATTACHMENT, $filename, 'report.csv')
        );
        $streamedResponse->headers->set('Content-Type', 'text/csv; charset=utf-8');
        $streamedResponse->headers->set('Content-Length', (string) strlen($csv));
        // Set here rather than relying on Security::init: those headers go on
        // the Response that App sends AFTER the controller has already streamed,
        // by which point headers_sent() is true and Symfony drops them.
        $streamedResponse->headers->set('X-Content-Type-Options', 'nosniff');
        $streamedResponse->headers->set('Cache-Control', 'no-store');

        return $streamedResponse->send();
    }

    /**
     * Same shape as AdminController's, so the step-up contract is identical
     * across every admin-sensitive action.
     */
    protected function stepUpForAdmin(
        Request $request,
        Response $response,
        MfaService $mfa,
        MfaLockout $lockout,
        Config $config
    ): array {
        if (! (bool) $config->get('step_up_auth', true)) {
            return ['ok' => true, 'used_backup' => false];
        }

        $current = $this->auth->user();
        $username = $current ? $current->getUsername() : '';
        if ($username === '') {
            $response->json('Not authenticated', 422);

            return ['ok' => false, 'used_backup' => false];
        }

        return $this->stepUpVerify(
            $response,
            $this->auth,
            $mfa,
            $lockout,
            $username,
            $request->getClientIp(),
            (string) $request->input('stepup_password', ''),
            (string) $request->input('stepup_code', ''),
            (bool) $request->input('stepup_use_backup', false)
        );
    }
}
